version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./:/app
    container_name: resume-tailor-backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    container_name: resume-tailor-frontend 